### ISSUE TITLE
Handling of renamed items

### ISSUE THREAD

**Issue by jnbuehler** [kamsar/Unicorn#110]
I believe this is just a simple case of an Item that got renamed, no corruption:

Duplicate serialized item IDs were detected (c2786c9c-b267-4dd8-b8fb-4452a23f9969) - this usually indicates corruption in the serialization provider data.
Item 1: master:/sitecore/system/Modules/E-mail Campaign Manager/System/Message Types/Ad-hoc (c2786c9c-b267-4dd8-b8fb-4452a23f9969)
Item 1 ProviderId: C:\sitecore\………\web\Website\data\Unicorn\Default Configuration\system\system\Modules\E-mail Campaign Manager\System\Message Types\Ad-hoc.yml
Item 2: master:/sitecore/system/Modules/E-mail Campaign Manager/System/Message Types/OneTime (c2786c9c-b267-4dd8-b8fb-4452a23f9969)
Item 2 ProviderId: C:\sitecore\………\web\Website\data\Unicorn\Default Configuration\system\system\Modules\E-mail Campaign Manager\System\Message Types\OneTime.yml
ERROR: Mindestens ein Fehler ist aufgetreten. (System.AggregateException)
bei Unicorn.Loader.SerializationLoader.LoadTreeInternal(IItemData root, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
bei Unicorn.Loader.SerializationLoader.LoadTree(IItemData rootItemData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
bei Unicorn.Loader.SerializationLoader.LoadAll(IItemData[] rootItemsData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
bei Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, IItemData[] roots)
bei Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.SyncVerb.Process(IProgressStatus progress, ILogger additionalLogger)
Consistency check failed - aborting loading. (Unicorn.Loader.ConsistencyException)
bei Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
bei Unicorn.Loader.SerializationLoader.LoadOneLevel(IItemData rootSerializedItemData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker)
bei Unicorn.Loader.SerializationLoader.<>c__DisplayClass15_0.b__1()

**Comment by kamsar** [comment]
This would indeed be an item that was renamed, but it's still corruption. I would guess a bad merge in source control left the same item on disk both in its pre-rename and post-rename location.

Unicorn keeps track of item IDs it's seen during a sync and if it finds the same ID more than once it throws this exception because it cannot be sure which of the renamed versions to load.

To fix the issue, you need to track down which name is the correct one and delete the wrongly named file.

In this case the file candidates are:
`C:\sitecore\………\web\Website\data\Unicorn\Default Configuration\system\system\Modules\E-mail Campaign Manager\System\Message Types\Ad-hoc.yml`
and
`C:\sitecore\………\web\Website\data\Unicorn\Default Configuration\system\system\Modules\E-mail Campaign Manager\System\Message Types\OneTime.yml`

One of those files needs to be deleted.
