### ISSUE TITLE
Incorrect YML file

### ISSUE THREAD

**Issue by eris86** [kamsar/Unicorn#143]
The YML file from Habitat has an error when trying to validate it. The error is, can't escape character inside the quoted string. 

The YML file is:
Habitat-master\src\Feature\Accounts\serialization\Feature.Accounts.Templates\Accounts\_AccountsSettings\Accounts\AccountsDetailsPage

The problematic line is 
` Value: "ar|Everyone|pe|+field:read|!*|pd|!*|+field:read|ar|modules\Feature Accounts Admin|pe|+field:write|pd|+field:write|"
`

**Comment by kamsar** [comment]
This is due to the backslash in `modules\Feature Accounts Admin`.

Fixing this is an interesting proposition because it to some extent is a format change. However, I think if we make the presence of `\` a trigger to use the multiline YAML format, that would enable forward and backwards compatibility.

That'd be done here https://github.com/kamsar/Rainbow/blob/master/src/Rainbow.Storage.Yaml/YamlWriter.cs#L62

On reserialization values containing `\` would become "multi-line" where the escaping is not needed. Existing items would not be touched.

We should also do the same for values containing literal double quotes, which would become `\"` in a YAML double-quote string. See http://stackoverflow.com/a/21699210 for a handy table of what escapes when in YAML.

**Comment by kamsar** [comment]
This will be fixed in the next version. Values containing \ and " will be placed on multiline format, where they do not need escaping. This preserves complete backwards compatibility in the format while also making it valid YAML.

Note: That the format was previously not valid YAML does not indicate that the Unicorn parser was malfunctioning in any way - just that the format wasn't quite YAML spec :)

**Comment by kamsar** [comment]
Released in 3.3.1
