### ISSUE TITLE
Sync is not updating the BranchId of an existing item

### ISSUE THREAD

**Issue by tonycwang** [kamsar/Unicorn#144]
I've noticed the following CommerceConnect items are not being updated when performing a Sync.

- /sitecore/system/Settings/Rules/Definitions/Elements/CommerceConnect Conditional Renderings/Tags
- /sitecore/system/Settings/Rules/Definitions/Elements/CommerceConnect Conditional Renderings/Tags/Default
- /sitecore/system/Settings/Rules/Definitions/Elements/CommerceConnect Conditional Renderings/Visibility
- /sitecore/system/Settings/Rules/Definitions/Elements/CommerceConnect Workflows/Tags
- /sitecore/system/Settings/Rules/Definitions/Elements/CommerceConnect Workflows/Tags/Default
- /sitecore/system/Settings/Rules/Definitions/Elements/CommerceConnect Workflows/Visibility

When comparing the re-serialized files, from my local instance, with the serialized files, from source control, used to sync I noticed that my local does not have a BranchId and the version from source control does have a BranchId.

Per the output messages on the Unicorn page after performing a sync, no items are being updated.  It's as if Sync does not detect a change is present between the local instance item and the serialized item.

I've verified that the BranchId GUID value is a valid branch item in my local instance.  When I removed one of the items before performing the Sync, Sync created that item as expected.  

We are using Unicorn 3.2 on Sitecore 8.1 Update 2.

**Comment by kamsar** [comment]
I suspect this to be due to BranchID being a root item data point (not a shared nor versioned field) and the `ItemComparer` is only checking for altered fields, parents, and templates.

Ref: https://github.com/kamsar/Rainbow/blob/master/src/Rainbow/Diff/ItemComparer.cs#L67

So basically _if the only change is BranchID_ it won't be picked up on. We should add an additional check to the diff to verify that branch ID is also matching.

While we're at it, the method name on https://github.com/kamsar/Rainbow/blob/master/src/Rainbow.Storage.Sc/Deserialization/DefaultDeserializer.cs#L147 is bad since it also deals with branch ID not just name. It ought to be two separate methods from a maintainability perspective, but it's one for performance.

**Comment by kamsar** [comment]
This will be fixed in the next version. As suspected, branch ID was not being correctly compared when diffs were being taken. Now it is.

**Comment by kamsar** [comment]
Released in 3.3.1

**Comment by cassidydotdk** [comment]
Relates to #283 

Turns out, messing with the BranchId has severe side effects.
