### ISSUE TITLE
Log warning if (unsupported) xpath/fast query is used with transparent sync

### ISSUE THREAD

**Issue by hermanussen** [kamsar/Unicorn#196]
Currently, when you use an xpath or fast query and transparent sync is enabled, nothing is returned from Unicorn.

This is ok, as we know that this is unsupported by Unicorn and this method of using Sitecore's content API is generally regarded as a bad practice anyway.

But it would be nice if Unicorn could log a warning, so that we can see that this is happening. It could help us determine the cause of problems related to this.

**Comment by kamsar** [comment]
Added in 1ab802c. Because you can't really tell if a query will match items under a transparent sync easily, I made it warn on _any_ usage of Fast Query. Which I'm totally fine with!

There is also a setting to turn off the logging if you are running something fast query heavy and can't live without it or transparent sync.

**Comment by kamsar** [comment]
This will be in the next Unicorn release.

**Comment by kamsar** [comment]
This will be in 4.0.
