### ISSUE TITLE
Allow exceptions to not include children

### ISSUE THREAD

**Issue by mortenbock** [kamsar/Unicorn#251]
Currently, when using the `<except/>` feature, the exception goes for all children as well, since the code just uses a "startswith":

https://github.com/kamsar/Unicorn/blob/f63a9edc961d13118c7a4f11a3fc878ab2804746/src/Unicorn/Predicates/Exclusions/ChildrenOfPathBasedPresetTreeExclusion.cs#L41

Given a scenario where I have a tree like this:

- MySite
- - DK
- - - SiteData
- - - - SiteConfig
- - - - Widgets
- - - - - Test widget
- - - Test page 1
- - - Test page 2

In my development environment, I would like to use transparent sync for the whole "MySite" tree.

I would do that with an include like:

    <include name="Content" database="master" path="/sitecore/content/MySite" />

Then on my QA/Stage/Prod servers, I only want to import some of the items:

- MySite
- - DK
- - - SiteData
- - - - SiteConfig
- - - - Widgets

I would change the Unicorn config to:

    <include name="Content" database="master" path="/sitecore/content/MySite">
      <exclude childrenOfPath="DK">
    	<except name="SiteData"/>
      </exclude>
    </include>

The problem with this is, that it still includes the `MySite/DK/SiteData/Widgets/Test widget` item.

What I would like to be able to do is something like:

    <include name="Content" database="master" path="/sitecore/content/MySite">
      <exclude childrenOfPath="DK">
    	<except name="SiteData" includeChildren="false"/>
    	<except name="SiteData/SiteConfig" includeChildren="false"/>
    	<except name="SiteData/Widgets" includeChildren="false"/>
      </exclude>
    </include>

So a way to make an exception for an item, that is not recursive for all descendant items.

**Comment by mortenbock** [comment]
I would be happy to make a PR for this btw. Just wanted to hear your thoughts :)

**Comment by kamsar** [comment]
Generally speaking favoring more include-based architecture tends to result in easier to read results. I get where you're going with this but it's fairly hard to read.

Were I in your situation, I think I'd probably approach the problem by either:
1) Adjusting the Sitecore structure so that items that were non-developerish items were not intermixed with developerish items (though this may also be difficult)
2) Splitting content into two configurations, one specifically for widgets, and the other set up the way you originally suggested, ignoring all of SiteData on qa/stage/prod and transparent-sync on dev. The widgets configuration would be fine on dev, as an item is ok in two separate configurations.

That said, if you want to implement this and update the test cases to include it, I'd probably merge it.

**Comment by mortenbock** [comment]
Added a PR here: https://github.com/kamsar/Unicorn/pull/252

**Comment by kamsar** [comment]
Closing this in favor of the PR. May take me a bit to get to the review with Symposium coming up :)
