### ISSUE TITLE
After config change items not picked up on serialization unless changes happen to them

### ISSUE THREAD

**Issue by uandrei** [kamsar/Unicorn#41]
If you change the config file after the initial serialization the module will not check if items are serialized or not. 

I've already created some items and then decided I'll need them serialized so I've changed the config file, but the new paths didn't show up on the disk until I've done a change to all the items in question.

**Comment by kamsar** [comment]
This is expected behavior, as there's no way to know whether a serialization root is empty intentionally (e.g. remove all items) or by accident. When changing the configuration, you should:

1. Run a sync, to make sure everything is up to date
2. Change the configuration to add the new items
3. Use the control panel to Reserialize that configuration (flushing the whole configuration, including the added paths, to disk)

If you're not using a custom serialization root, you can also serialize the added tree using the Developer tab in the content editor (standard Sitecore functionality) for the same effect.
