### ISSUE TITLE
Unchecked checkboxes are not serialised

### ISSUE THREAD

**Issue by Eldblom** [kamsar/Unicorn#74]
When checkboxes is default checked, unchecking it on an item, the value 0 (zero) is not serialised.

To recreate:
1. Create a checkbox field on a template
2. Set the standard value for the field to checked.
3. Create an item based on the template
4. Uncheck the checkbox
5. Do a clean install
6. Sync the item back
7. Check that the checkbox field is checked

**Comment by kamsar** [comment]
Good catch, I think this can be fixed with a field formatter to override the way checkboxes are stored.

**Comment by kamsar** [comment]
Implementation notes:

* On reflection a field formatter is not a correct solution as checkboxes are not the only case where standard values could result in _significant blank values_ (e.g. a text field could also have a blank value overriding a standard value). We need to alter the way `ItemData` parses fields to grab fields both using standard values and not using standard values (right now it gets them without only), then return explicit blanks for fields which have a standard value but their value without the standard value differs. Note that we have to avoid using `field.IsStandardValue` because that does not use cache and is ungodly slow. I'm pretty sure that if `ItemData` returns a field with a blank value, it'll make it into YAML.
* Does setting an empty value in YAML cause the deserializer to consider it significant and set the field to blank? Probably. If so, can get away without needing a property to signify an important empty value.

**Comment by kamsar** [comment]
@Eldblom thanks for finding this. I believe I've fixed the problem in a way that solves it for all field types, not just checkboxes - vetted both by tests and comparing a whole serialized copy of the core db which included several items that were affected by this bug. I'll release a new version of Unicorn soon that will include this fix.

**Comment by Eldblom** [comment]
Great. Looking forward to the release
