### ISSUE TITLE
Transparent sync missing item changes when templates and content under same config?

### ISSUE THREAD

**Issue by kamsar** [kamsar/Unicorn#76]
via @Hermanussen

knifecore [9:16 AM] 
@kamsar: Hey Kam, I'm seeing content item field changes being immediately reverted using Unicorn 3 with transparent sync. Within the same configuration, it does work for changing fields on items under /sitecore/templates. Logs show no problems and the .yml files actually get updated timestamps on the filesystem. Any ideas?

Kam Figy [9:26 AM] 
hmm so you've got a config with content and templates together that are under tpsync, and you're seeing updates saved to the content items not save. Correct?

Kam Figy [9:40 AM] 
@knifecore does clearing the data cache result in the lost updates 'appearing'?

knifecore [9:44 AM] 
Correct. I'll try that. Just a sec.

knifecore [9:45 AM]
Nope. Lost updates don't reappear.

Kam Figy [9:46 AM] 
huh but they are written to disk?

knifecore [9:47 AM] 
You would think so, as the timestamp on the .yml file is changed. But the change isn't reflected in the file.

Kam Figy [9:48 AM] 
hmm. Are the templates and/or content items not in the database as well? (the editor warning should indicate if it is or not)

Kam Figy [9:48 AM]
specifically the content item, and the template it's based on

knifecore [9:50 AM] 
No indication of that in the warning. I have only just serialized everything, so the items in the database should be very similar. I'll check to see if changes are visible in the database.

Kam Figy [9:50 AM] 
hmm, which unicorn version are you on and does the warning say 'under transparent sync'?

Kam Figy [9:51 AM]
if on the latest, and it knows it's transparent sync, the database indication would be at the end of the details iirc

knifecore [9:53 AM] 
Actually, the changes ARE written to the database. I'm on 3.0.1.1.  The warning says: This item is included by Unicorn Transparent Sync

knifecore [9:53 AM]
Item exists in the Sitecore database as well as Transparent Sync.

Kam Figy [9:54 AM] 
hmm. and since you just serialized this all the template almost certainly is in the db too huh

knifecore [9:54 AM] 
Yes

**Comment by hermanussen** [comment]
Hi Kam. I've actually done some more research, and have isolated the issue a bit more.

It's not related to whether or not the items and templates are in the same configuration. I thought it might be, and I noticed things working flawlessly with templates. But that's because the templates are defined in the 'en' language, and our content is not.

So actually, it's a language issue. The described behavior only occurs with saving field values in languages other than 'en'.

Oddly enough, that's even the case with shared fields! If I save a value in a shared field when viewing the item in 'en', it gets saved to the filesystem and works correct. If I switch to a different language, I can't even see that value and when changing it nothing changes on the filesystem.

I'm going to turn off transparent sync for now. I'll let you know if that works.

**Comment by hermanussen** [comment]
Ok, so after turning off transparent sync, it still doesn't work. But it becomes less apparent, because items are written to the database and retrieved from there correctly.

Things get really weird now... the following happens (initial state is that item in Sitecore and .yml file are in sync):
1. Change a field value in a language other than 'en' within the .yml file
2. Use the revert item function to deserialize the item into Sitecore
3. The change is correctly reflected in Sitecore
4. The .yml file now has the data that was previously in Sitecore, effectively undoing step 1!

Now, the other way around (initial state is the same as before):
1. Change a field value in a language other than 'en' within Sitecore
2. Save the item
3. The change is NOT correctly reflected in the .yml file
4. Use the serialize item function to serialize the item to the .yml file
5. Now the change IS correctly reflected in the .yml file

**Comment by kamsar** [comment]
Thanks for the research, will save me a lot of time :)

**Comment by kamsar** [comment]
Fixed in https://github.com/kamsar/Unicorn/commit/f83a02c4b5537d1a4414afe190cf465da4c5b434

Thank you for finding this. Feel free to curse us darn Americans and our single language myopia now ;)
