### ISSUE TITLE
One item is always updated on each sync run

### ISSUE THREAD

**Issue by demisx** [kamsar/Unicorn#84]
We have an item that is aways updated each time we run Unicorn 3.0.2 sync, even if no changes were made. The Unicorn window shows:

```
[U] master:/sitecore/media library/rendering-thumbnails/grid-2x1-6-1-5 (3c052857-b17a-4b72-a024-386972c08691)
> New version de-AT#1 (serialized)
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
* [U] en#1: __Created
```

My understanding, that all database items should be updated only on first run and then skipped in the subsequent runs if no changes were made. Any idea what can be causing this behavior?

**Comment by kamsar** [comment]
Issues like this are usually due to altered standard values. The sync compares WITHOUT standard values (because you don't want to overwrite standard values if they are set).

So if you have item _x_ with field _y_, and you set _y_ to "hello" and then later set _y_'s standard value to "hello", _x_ may well appear to be updated each time. I've seen __Created cause this issue before as Sitecore does have a standard value for that.

In this case, verify also that the language (de-AT) exists.

**Comment by demisx** [comment]
Thank you for the explanation. Makes sense.
