### ISSUE TITLE
Issue serializing uCommerce for Sitecore items

### ISSUE THREAD

**Issue by devstack** [kamsar/Unicorn#87]
I'm using Sitecore 8.1 and have installed uCommerce for Sitecore 6.8.3.15293

The product works perfectly for everything else but having problems getting Unicorn to serialize any of the items created by uCommerce. Changes are made to definition items (templates) but unicorn doesn't recognize any changes yet the path is included in my configuration.

Any help / fix would be hugely appreciated as I can't seem to find anything online related to this problem.

**Comment by kamsar** [comment]
I believe uCommerce uses its own data provider, which may in fact be storing these items in its own database or something similar. Sitecore supports multiple data providers, but a given data provider may abort the others if it so chooses - thus causing Unicorn to not see the updates.

I don't have any experience with uCommerce (the above was from a previous bug someone reported around the Unicorn data provider and uCommerce that we fixed by altering the order in which Unicorn was registered as a data provider). Your best way forward would be to use `/sitecore/admin/showconfig.aspx` to review the final data provider registrations and look for issues. You may also need to install Unicorn from source to do some debugging, or potentially implement a uCommerce-aware Unicorn data provider (see `UnicornSqlServerDataProvider.cs` for a template when wrapping another data provider).
